# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 2.4.0"

gem "ckb-sdk-ruby", git: "https://github.com/nervosnetwork/ckb-sdk-ruby.git", require: "ckb", tag: "v0.24.0"
gem 'money-tree'
